/* ──────────────────────────────────────────────────
   data.js  — 다국어 텍스트 + 언어 목록
   지원: English / Tiếng Việt / 中文 / ខ្មែរ / ภาษาไทย / 한국어
   3열 그리드, 6개 버튼 (빈 칸 없음)
────────────────────────────────────────────────── */

const LANGUAGES = [
  { code: "en", cc: "us", flag: "🇺🇸", label: "English" },
  { code: "vi", cc: "vn", flag: "🇻🇳", label: "Tiếng Việt" },
  { code: "zh", cc: "cn", flag: "🇨🇳", label: "中文" },
  { code: "km", cc: "kh", flag: "🇰🇭", label: "ខ្មែរ" },
  { code: "th", cc: "th", flag: "🇹🇭", label: "ภาษาไทย" },
  { code: "ko", cc: "kr", flag: "🇰🇷", label: "한국어" },
];

const T = {
  ko: {
    pinPrompt:    "전화번호 뒷자리 4자리를 입력하세요",
    greeting:     "안녕하세요!",
    helmetName:   "안전모",
    vestName:     "안전조끼",
    wearCheck:    "착용 필수",
    scanLabel:    "PPE 착용 상태를 확인하고 있습니다",
    startScan:    "촬영 시작",
    passMsg:      "안전 장비 착용 확인 완료! 안전한 하루 되세요.",
    failMsg:      "안전 장비 미착용이 감지되었습니다. 착용 후 재시도해 주세요.",
    retryBtn:     "다시 시도",
    nextBtn:      "다음 작업자",
    resetBtn:     "처음으로",
    guidTitle:    "착용 방법 안내",
    guide: [
      "안전모를 머리에 올바르게 착용하세요.",
      "안전조끼를 입고 지퍼/버튼을 잠가주세요.",
      "카메라 정면을 바라보고 촬영하세요.",
    ],
    escalationNative: "관리자를 호출합니다.",
    escalationKo:     "3회 연속 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "통과",
    ttsFailed:   "미통과",
  },
  en: {
    pinPrompt:    "Enter the last 4 digits of your phone number",
    greeting:     "Hello!",
    helmetName:   "Hard Hat",
    vestName:     "Safety Vest",
    wearCheck:    "Required",
    scanLabel:    "Checking your PPE…",
    startScan:    "Start Scan",
    passMsg:      "PPE check complete! Have a safe day.",
    failMsg:      "Missing PPE detected. Please wear your equipment and try again.",
    retryBtn:     "Retry",
    nextBtn:      "Next Worker",
    resetBtn:     "Back to Start",
    guidTitle:    "How to wear PPE",
    guide: [
      "Put on your hard hat correctly.",
      "Wear your safety vest and fasten it.",
      "Face the camera and take the photo.",
    ],
    escalationNative: "Calling supervisor.",
    escalationKo:     "3 failures — a supervisor will arrive shortly.",
    ttsPassed:   "Passed",
    ttsFailed:   "Failed",
  },
  zh: {
    pinPrompt:    "请输入手机号后4位",
    greeting:     "你好！",
    helmetName:   "安全帽",
    vestName:     "安全背心",
    wearCheck:    "必须佩戴",
    scanLabel:    "正在检测安全装备…",
    startScan:    "开始扫描",
    passMsg:      "安全装备检测完成！祝您工作顺利。",
    failMsg:      "检测到未佩戴安全装备，请穿戴后重试。",
    retryBtn:     "重试",
    nextBtn:      "下一位",
    resetBtn:     "返回首页",
    guidTitle:    "佩戴方法指引",
    guide: [
      "正确戴上安全帽。",
      "穿上安全背心并扣好。",
      "面向摄像头拍照。",
    ],
    escalationNative: "正在呼叫主管。",
    escalationKo:     "연속 3회 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "通过",
    ttsFailed:   "未通过",
  },
  vi: {
    pinPrompt:    "Nhập 4 số cuối số điện thoại của bạn",
    greeting:     "Xin chào!",
    helmetName:   "Mũ bảo hộ",
    vestName:     "Áo phản quang",
    wearCheck:    "Bắt buộc",
    scanLabel:    "Đang kiểm tra thiết bị bảo hộ…",
    startScan:    "Bắt đầu quét",
    passMsg:      "Kiểm tra PPE hoàn tất! Chúc bạn một ngày làm việc an toàn.",
    failMsg:      "Phát hiện thiếu PPE. Hãy mặc đầy đủ và thử lại.",
    retryBtn:     "Thử lại",
    nextBtn:      "Người tiếp theo",
    resetBtn:     "Về đầu",
    guidTitle:    "Hướng dẫn mặc PPE",
    guide: [
      "Đội mũ bảo hộ đúng cách.",
      "Mặc áo phản quang và cài khóa.",
      "Nhìn thẳng vào camera để chụp.",
    ],
    escalationNative: "Đang gọi giám sát viên.",
    escalationKo:     "연속 3회 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "Đạt",
    ttsFailed:   "Không đạt",
  },
  th: {
    pinPrompt:    "กรอก 4 หลักสุดท้ายของเบอร์โทรศัพท์",
    greeting:     "สวัสดี!",
    helmetName:   "หมวกนิรภัย",
    vestName:     "เสื้อกั๊กนิรภัย",
    wearCheck:    "จำเป็น",
    scanLabel:    "กำลังตรวจสอบ PPE…",
    startScan:    "เริ่มสแกน",
    passMsg:      "ตรวจสอบ PPE เสร็จสมบูรณ์! ขอให้ทำงานอย่างปลอดภัย",
    failMsg:      "ตรวจพบว่าไม่สวมใส่ PPE กรุณาสวมใส่และลองใหม่",
    retryBtn:     "ลองอีกครั้ง",
    nextBtn:      "คนงานถัดไป",
    resetBtn:     "กลับหน้าแรก",
    guidTitle:    "วิธีสวมใส่ PPE",
    guide: [
      "สวมหมวกนิรภัยอย่างถูกต้อง",
      "ใส่เสื้อกั๊กนิรภัยและรัดให้แน่น",
      "หันหน้าเข้าหากล้องแล้วถ่ายรูป",
    ],
    escalationNative: "กำลังเรียกหัวหน้างาน",
    escalationKo:     "연속 3회 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "ผ่าน",
    ttsFailed:   "ไม่ผ่าน",
  },
  mn: {
    pinPrompt:    "Утасны дугаарын сүүлийн 4 оронг оруулна уу",
    greeting:     "Сайн уу!",
    helmetName:   "Хамгаалах малгай",
    vestName:     "Хамгаалах жилэт",
    wearCheck:    "Заавал өмс",
    scanLabel:    "PPE шалгаж байна…",
    startScan:    "Скан эхлүүлэх",
    passMsg:      "PPE шалгалт амжилттай! Аюулгүй өдөр өнгөрүүлээрэй.",
    failMsg:      "PPE өмсөөгүй байна. Өмсөөд дахин оролдоно уу.",
    retryBtn:     "Дахин оролдох",
    nextBtn:      "Дараагийн ажилтан",
    resetBtn:     "Эхлэл рүү буцах",
    guidTitle:    "PPE өмсөх заавар",
    guide: [
      "Хамгаалах малгайг зөв өмс.",
      "Жилэт өмсөж бүсэлнэ үү.",
      "Камерт харж зураг авахуулна уу.",
    ],
    escalationNative: "Ахлагчийг дуудаж байна.",
    escalationKo:     "연속 3회 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "Тэнцсэн",
    ttsFailed:   "Тэнцээгүй",
  },
  ru: {
    pinPrompt:    "Введите последние 4 цифры вашего телефона",
    greeting:     "Привет!",
    helmetName:   "Каска",
    vestName:     "Жилет безопасности",
    wearCheck:    "Обязательно",
    scanLabel:    "Проверка СИЗ…",
    startScan:    "Начать сканирование",
    passMsg:      "Проверка СИЗ завершена! Безопасного рабочего дня.",
    failMsg:      "Обнаружено отсутствие СИЗ. Наденьте и повторите попытку.",
    retryBtn:     "Повторить",
    nextBtn:      "Следующий работник",
    resetBtn:     "На главную",
    guidTitle:    "Инструкция по надеванию СИЗ",
    guide: [
      "Правильно наденьте каску.",
      "Наденьте жилет и застегните его.",
      "Встаньте перед камерой и сделайте фото.",
    ],
    escalationNative: "Вызываем руководителя.",
    escalationKo:     "연속 3회 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "Пройдено",
    ttsFailed:   "Не пройдено",
  },
  id: {
    pinPrompt:    "Masukkan 4 digit terakhir nomor telepon Anda",
    greeting:     "Halo!",
    helmetName:   "Helm Keselamatan",
    vestName:     "Rompi Keselamatan",
    wearCheck:    "Wajib dipakai",
    scanLabel:    "Memeriksa APD Anda…",
    startScan:    "Mulai Scan",
    passMsg:      "Pemeriksaan APD selesai! Semoga hari kerja Anda aman.",
    failMsg:      "APD tidak terdeteksi. Silakan kenakan dan coba lagi.",
    retryBtn:     "Coba Lagi",
    nextBtn:      "Pekerja Berikutnya",
    resetBtn:     "Kembali ke Awal",
    guidTitle:    "Cara memakai APD",
    guide: [
      "Pakai helm keselamatan dengan benar.",
      "Kenakan rompi dan kancingkan.",
      "Hadap kamera lalu ambil foto.",
    ],
    escalationNative: "Memanggil pengawas.",
    escalationKo:     "연속 3회 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "Lulus",
    ttsFailed:   "Tidak Lulus",
  },
  km: {
    pinPrompt:    "បញ្ចូលលេខទូរស័ព្ទ 4 ខ្ទង់ចុងក្រោយ",
    greeting:     "សួស្តី!",
    helmetName:   "មួកសុវត្ថិភាព",
    vestName:     "អាវក្រៅសុវត្ថិភាព",
    wearCheck:    "តម្រូវឱ្យពាក់",
    scanLabel:    "កំពុងពិនិត្យ PPE…",
    startScan:    "ចាប់ផ្តើមស្កែន",
    passMsg:      "ការពិនិត្យ PPE បានបញ្ចប់! សូមឱ្យមានសុវត្ថិភាព។",
    failMsg:      "រកឃើញ PPE មិនគ្រប់គ្រាន់។ សូមពាក់ហើយព្យាយាមម្តងទៀត។",
    retryBtn:     "ព្យាយាមម្តងទៀត",
    nextBtn:      "កម្មករបន្ទាប់",
    resetBtn:     "ត្រឡប់ទៅដើម",
    guidTitle:    "របៀបពាក់ PPE",
    guide: [
      "ពាក់មួកសុវត្ថិភាពឱ្យបានត្រឹមត្រូវ។",
      "ពាក់អាវក្រៅហើយចាក់ស្ទូច។",
      "ងាកមុខទៅកាមេរ៉ាហើយថតរូប។",
    ],
    escalationNative: "កំពុងហៅអ្នកគ្រប់គ្រង។",
    escalationKo:     "연속 3회 실패 — 담당자가 곧 도착합니다.",
    ttsPassed:   "ជាប់",
    ttsFailed:   "ធ្លាក់",
  },
};
